export const categoriesStoreSelf = [
  "Acolchadora",
  "Adaptador",
  "Auriculares",
  "Boletas",
  "Bolígrafo",
  "Bolsos",
  "Cables",
  "Calculadora",
  "Cargador de móvil",
  "Cargador",
  "Carpeta de anillas",
  "Carpeta de archivo",
  "Carpetas",
  "Cartucheras",
  "Celular",
  "Cinta adhesiva",
  "Clips",
  "Compás",
  "Corrector",
  "Cuaderno",
  "Diccionario",
  "Disco duro externo",
  "Folios",
  "Goma de borrar",
  "Gorras",
  "Grapadora",
  "Lámparas",
  "Lapices",
  "Lápiz",
  "Laptop",
  "Libreta de notas",
  "Libretas",
  "Libros",
  "Marcadores",
  "Mochila",
  "Módem",
  "Otros",
  "Pantalón",
  "Papelería",
  "Pilas",
  "Portaminas",
  "Post-it",
  "Pulseras",
  "Regla",
  "Resaltadores",
  "Sacapuntas",
  "Sueter",
  "Tableta",
  "Talonario",
  "Tijeras",
  "USB",
  "Zapatos",
];

export const state_product = [
  "Nuevo",
  "Usado - Como nuevo",
  "Usado - Buen estado",
  "Usado - Aceptable",
];
