export const arrayHabilities = [
  "Liderazgo",
  "Comunicación efectiva",
  "Trabajo en equipo",
  "Resolución de problemas",
  "Pensamiento crítico",
  "Comprensión de la industria",
  "Flexibilidad",
  "Iniciativa",
  "Adaptabilidad",
  "Conocimiento de la tecnología",
  "Creatividad",
  "Planificación",
  "Toma de decisiones",
  "Negociación",
  "Productividad",
  "Dominio de lenguas extranjeras",
  "Confiabilidad",
  "Confidencialidad",
  "Cumplimiento de normas y procedimientos",
  "Capacidad de trabajo bajo presión",
];

export const arrayRequirement = [
  "Título universitario o certificación profesional relevante",
  "Experiencia laboral previa en el área de trabajo",
  "Conocimientos y habilidades específicos",
  "Competencias profesionales y personales",
  "Disponibilidad para trabajar en cualquier horario",
  "Disponibilidad para trabajar en equipo",
  "Disponibilidad para trabajar bajo presión",
  "Capacidad para aprender nuevas habilidades",
  "Buenas habilidades de comunicación",
  "Flexibilidad para adaptarse a los cambios",
  "Disponibilidad para viajar",
  "Conocimiento de herramientas informáticas",
  "Capacidad para gestionar proyectos",
  "Capacidad para manejar conflictos",
  "Conocimiento de los productos y servicios ofrecidos por la empresa",
  "Buena atención al cliente",
  "Ganas de superación personal",
  "Capacidad para resolver problemas",
  "Responsabilidad y fiabilidad",
  "Buenas habilidades de organización",
];
