export function filtrarComentarios(comentario) {
  let palabrasVulgares = [
    "boba",
    "Bobo",
    "Cabron",
    "cabrón",
    "cabronada",
    "cabronazo",
    "cabronear",
    "Cachon",
    "Cachón",
    "cachona",
    "Calienta huevos",
    "Cara e monda",
    "chinga",
    "chingada",
    "chingar",
    "chingón",
    "chingue",
    "cojudeces",
    "cojudería",
    "cojudez",
    "cojudo",
    "culerada",
    "culero",
    "hijueputa",
    "hp",
    "hijueputada",
    "hijueputear",
    "Huevon",
    "Huevón",
    "Imbécil",
    "joder",
    "jodida",
    "jodido",
    "jodienda",
    "maldito",
    "maldit",
    "maldit0",
    "mamada",
    "mamarracho",
    "marica",
    "maricón",
    "mariconada",
    "mierda",
    "mierdero",
    "mierdoso",
    "m0nda",
    "mond@",
    "monda",
    "m@nda",
    "pendejada",
    "pendejear",
    "pendejo",
    "perra",
    "perro",
    "pinche",
    "pinche",
    "pinchería",
    "pinchería",
    "puta",
    "putada",
    "putear",
    "putería",
    "puterío",
    "puto",
    "sapo",
    "tonta",
    "tontear",
    "tonto",
    "verga",
    "vrg",
  ];
  let comentarioFiltrado = comentario;
  // Recorremos el array de palabras vulgares

  for (let i = 0; i < palabrasVulgares.length; i++) {
    // Reemplazamos la palabra malsonante por un asterisco
    comentarioFiltrado = comentarioFiltrado.replace(
      new RegExp(palabrasVulgares[i], "gi"),
      "*****"
    );
  }
  return comentarioFiltrado;
}
